arb-dir: lib/presentation/localization
output-dir: lib/generated
output-localization-file: app_localizations.dart
output-class: AppLocalizations
template-arb-file: app_en.arb
preferred-supported-locales: [en, es]
nullable-getter: false
untranslated-messages-file: untranslated.json