name: glpi_client_advanced
version: 2.0.0+1
publish_to: 'none'

description: "Advanced GLPI Client - Multiplatform Flutter application with AI integration, local awareness, and geographic location support"

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # HTTP client with advanced features
  dio: ^5.7.0
  
  # State management with Riverpod
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  
  # JSON serialization
  json_annotation: ^4.8.1
  
  # Secure storage for tokens and sensitive data
  flutter_secure_storage: ^9.2.2
  
  # Shared preferences for app settings
  shared_preferences: ^2.3.2
  
  # Local database
  sqflite: ^2.4.0
  path: ^1.9.0
  
  # Geographic location
  geolocator: ^12.0.0
  geocoding: ^2.2.0
  
  # Window management for desktop
  window_manager: ^0.3.7
  
  # Platform specific paths
  path_provider: ^2.1.5
  
  # AI integration
  http: ^1.2.2
  
  # Internationalization
  intl: ^0.20.2
  
  # Date formatting
  intl_utils: ^2.8.7
  
  # URL launcher for web links
  url_launcher: ^6.3.0
  
  # File picker for attachments
  file_picker: ^8.1.2
  
  # Image handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  
  # Animations
  animations: ^2.0.8
  
  # Connectivity check
  connectivity_plus: ^5.0.2
  
  # Device information
  device_info_plus: ^9.1.0
  
  # Package info
  package_info_plus: ^9.0.0
  
  # Material design icons
  cupertino_icons: ^1.0.8

  # Charts for analytics
  fl_chart: ^0.64.0
  
  # PDF generation
  pdf: ^3.10.0
  printing: ^5.11.0

dependency_overrides:
  # Ensure compatibility
  collection: ^1.19.0
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  
  # Testing
  mockito: ^5.4.2
  build_runner_core: ^8.0.0


  dartz: ^0.10.1 

flutter:
  uses-material-design: true
  
  # Enable generation of localized strings
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
    - assets/config/
    - assets/fonts/
    

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono-Medium.ttf
          weight: 500